
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqs6trEd2Lm0RdaZOHAmqkriAUShbi-pg',
    appId: '1:737278449708:web:9365647998c9b77ae95989',
    messagingSenderId: '737278449708',
    projectId: 'esp32-smart-home-5643e',
    authDomain: 'esp32-smart-home-5643e.firebaseapp.com',
    databaseURL: 'https://esp32-smart-home-5643e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-smart-home-5643e.firebasestorage.app',
    measurementId: 'G-7C1R74PHBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuLjkcfM81SGZnlxuH1wRJ55Sfem1J6pk',
    appId: '1:737278449708:android:7c4e24edcbd7bfcae95989',
    messagingSenderId: '737278449708',
    projectId: 'esp32-smart-home-5643e',
    databaseURL: 'https://esp32-smart-home-5643e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-smart-home-5643e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIkavU0SPRNJUBGttfWsT2RiDSOkZO7s',
    appId: '1:737278449708:ios:1fb20953ea83c8cde95989',
    messagingSenderId: '737278449708',
    projectId: 'esp32-smart-home-5643e',
    databaseURL: 'https://esp32-smart-home-5643e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-smart-home-5643e.firebasestorage.app',
    iosBundleId: 'com.example.espHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIkavU0SPRNJUBGttfWsT2RiDSOkZO7s',
    appId: '1:737278449708:ios:1fb20953ea83c8cde95989',
    messagingSenderId: '737278449708',
    projectId: 'esp32-smart-home-5643e',
    databaseURL: 'https://esp32-smart-home-5643e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-smart-home-5643e.firebasestorage.app',
    iosBundleId: 'com.example.espHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqs6trEd2Lm0RdaZOHAmqkriAUShbi-pg',
    appId: '1:737278449708:web:df40f6bd4c448596e95989',
    messagingSenderId: '737278449708',
    projectId: 'esp32-smart-home-5643e',
    authDomain: 'esp32-smart-home-5643e.firebaseapp.com',
    databaseURL: 'https://esp32-smart-home-5643e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-smart-home-5643e.firebasestorage.app',
    measurementId: 'G-LDLMZ87VCY',
  );
}
